### ISSUE TITLE
Versioning not working with copyDirectory

### ISSUE THREAD

**Issue by bornemisza** [laravel-mix/laravel-mix#2412]
-   Laravel Mix Version: 5.0., 5.0.4
-   Node Version: v12.16.3
-   NPM Version: 6.14.4
-   YARN Version: 1.22.4
-   OS: Linux (ubuntu 20.4), Windows 10

### Description:

I could not find the matching issue about copyDirectory and versioning issue. If I am right, the Mix should versioning the copyDirectory compiled assets too, not just with copy function. I ran into this issue when I used the Laravel Blade mix() function in template to include assets. (error: 'Unable to locate Mix file')

**webpack.mix.js:**
mix
    .copyDirectory('node_modules/cookieconsent/build', 'public/vendor/cookieconsent')
    .copyDirectory('node_modules/fomantic-ui/dist', 'public/vendor/fomanticui')
    .copy('node_modules/jquery/dist/jquery.min.js', 'public/vendor/jquery')
    .version();

**mix-manifest.json:**
{
    "/vendor/jquery/jquery.min.js": "/vendor/jquery/jquery.min.js?id=dc5e7f18c8d36ac1d3d4"
}

All of the compiled assets placed in the expected folder, only the versioning not working with copyDirectory.

Other issues mentioned the dotting problem, when folder or file had dot in name. Honestly feels like I misunderstood something.

### Steps To Reproduce:

Required and base information above.

Command used: "yarn watch"

**Comment by garbinmarcelo** [comment]
Hello, did you manage to solve this? I'm trying to version layout images that are in subfolders, but without success.

**Comment by bornemisza** [comment]
> 
> 
> Hello, did you manage to solve this? I'm trying to version layout images that are in subfolders, but without success.

Sadly, I could not.

**Comment by garbinmarcelo** [comment]
I also tried to do some searches about it and found nothing about it, it seems to be something that is still missing for Laravel Mix. It would be nice to have this because sometimes it happens that the name of an image can be the same, but the content of it can be different. This ended up with cache problem

**Comment by o15a3d4l11s2** [comment]
I have the same problem. `copyDirectory` works, `version` works for the files that are in the main directory I am copying, but the files in the subdirectories are not listed in `mix-manifest.json` and therefore not versioned. Is there any solution to this?

**Comment by dionowl** [comment]
+1 REOPEN THIS

**Comment by kapitannwel** [comment]
+1 REOPEN THIS

**Comment by dynamicnet** [comment]
Same here with mix 6.0.19

**Comment by Rizky92** [comment]
I use this code in my projects. It read through all files and folders on given path and version it. It only does at one level though. So anything beyond 2 levels might require more gotchas, or use recursive implementation.

```
const mix = require('laravel-mix');
const fs = require('fs');
const path = require('path');

mix.extend('copyAllDirectories', (webpackConfig, from, to) => {
    from = `${path.parse(from).dir}/${path.parse(from).name}`;

    let input = fs.readdirSync(from, { withFileTypes: true })
        .map(dir => !dir.isDirectory()
            ? dir.name
            : fs.readdirSync(`${from}/${dir.name}`).map(file => `${dir.name}/${file}`)
        )
        .flat();

    to = `${path.parse(to).dir}/${path.parse(to).base}`;

    input.forEach(file => mix.copy(`${from}/${file}`, `${to}/${file}`));
});
```
e.g.
Given following directory within `resource/assets` folder:
```
'foo1/bar.jpg',
'foo2/bar.jpg',
'foo3/bar.jpg',
'baz.png',
```
with output to `public/assets` can be done by
```
mix.copyAllDirectories('resources/assets', 'public/assets')
```
will be able to version each of them, preserving its original path
```
'public/assets/foo1/bar.jpg',
'public/assets/foo2/bar.jpg',
'public/assets/foo3/bar.jpg',
'public/assets/baz.png',
```

**Comment by o15a3d4l11s2** [comment]
Thanks, @Rizky92, I was also planning on trying something similar. I will try this solution when I have time and give feedback.

**Comment by inboundsan** [comment]
@Rizky92 
Thanks this works.
