### ISSUE TITLE
[6.*] Combine not working

### ISSUE THREAD

**Issue by thisisjamessmith** [laravel-mix/laravel-mix#2624]
### Description:

Hiya, thanks for Mix! I'm trying to upgrade to version 6 and finding that `combine` is not working for me when it was ok in Mix 5. I've put together a fully reduced test repo here demonstrating the issue: https://github.com/cld-agency/mix6-test

The repo contains two CSS files (one SCSS and one plain CSS, though I've tried with two CSS files and using the postCSS command for both, with the same results). I compile them and then combine them into combined.css. The combined.css file gets created but is always blank.

### Steps To Reproduce:

* clone the test repo: https://github.com/cld-agency/mix6-test
* `npm install`
* `npm run prod`

-   Laravel Mix Version: 6.0.0-beta.14
-   Node Version: 14.15.0
-   NPM Version: 6.14.8
-   OS: MacOS 10.15.7

When doing npm install I do get a deprecation warning - not sure if this has any bearing on the issue, but I can't find a way to make this warning go away!

```
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

**Comment by JeffreyWay** [comment]
Thanks, I'll have a look this week.

**Comment by ezra-obiwale** [comment]
@JeffreyWay Any updates on this, please?

**Comment by dmocho** [comment]
@JeffreyWay

This actually does work but incorrectly.
`combine`/`styles` is executed in parallel to `sass`/`less`/etc.
As a result the concatenated file is empty or only contains any pre-built/static content.
In the provided repro if the files were not cleaned after concatenation then second run of `mix` would provide correct results.
But in that case cleaning up is not possible...

**Comment by maiconmva** [comment]
+1 

upgraded to latest version and broken my script!! 

i cant compile and after that combine
