### ISSUE TITLE
[v6.0.0-beta.14] VueJS - vue-loader `shadowMode`

### ISSUE THREAD

**Issue by SergkeiM** [laravel-mix/laravel-mix#2643]
-   Laravel Mix Version: `v6.0.0-beta.14`
-   Node Version (`node -v`): `12.14.1`
-   NPM Version (`npm -v`): `6.13.4`
-   OS: `Windows 10`

### Description:

Hi, I'm trying to implement webcomponents using [Vue](https://github.com/vuejs/vue-web-component-wrapper).

And using SFC, to inject CSS/SCSS into shadow DOM, Based on this [comment](https://github.com/vuejs/vue-web-component-wrapper/issues/11#issuecomment-377928242), Enabling `shadowMode: true` in `vue-loader` should append the styles into `this.$root.shadowRoot` insted of `<head>`.

### Steps To Reproduce:

My Mix config
```javascript
const mix = require('laravel-mix');

mix.options({
	vue: {
	    shadowMode: true //set shadowMode: true for vue-loader
  	}
});

mix.js('src/index.js', 'dist/webcomponents.js').setPublicPath('dist');
```

Index.js

```javascript
import Vue from "vue";
import wrap from "@vue/web-component-wrapper";

import Test from "./Test";

const wrappedElement = wrap(Vue, Test);

window.customElements.define("test-component", wrappedElement);
```

Test.vue
```javascript
<template>
  	<div>
    	<h1>{{ title }}</h1>
  	</div>
</template>
<style lang="scss">
	h1{
      	color: var(--h1-color, red);
    }
</style>
<script>
	export default {
	  	props: {
	    	title: {
	      		type: String,
	      		default: "Test"
	    	},
	  	}
	};
</script>
```

But all styles are still shown in `<head>`, tried using `laravel-mix v6`, but still the same, any suggestion?

**Comment by thecrypticace** [comment]
We should add a way to pass arbitrary options to `vue-loader`. I'll open a PR for that this evening

**Comment by thecrypticace** [comment]
Heh I already did this for Mix v6.

```js
mix.vue({
  options: {
    shadowMode: true,
  },
})
```

**Comment by Froxz** [comment]
Hi @thecrypticace, thank you for reply.

I tried Mix v6, doesn't work, I will prepare a `codepen`

**Comment by Froxz** [comment]
Hi @thecrypticace

Laravel Mix Version: `v6.0.0-beta.14`
vue-loader Version: `15.9.5`

Mix Config
```javascript
const mix = require('laravel-mix');

mix.js('src/index.js', 'dist/webcomponents.js').vue({
	version: 2,
	options: {
	    shadowMode: true
	}
}).setPublicPath('dist');
```

Same compontent as above, output:

![shadow-css](https://user-images.githubusercontent.com/3294939/100920676-2271c000-34e4-11eb-881c-68db1a74cc97.png)


Do I miss something?

**Comment by thecrypticace** [comment]
That seems right to me. I'll take another look.

**Comment by Froxz** [comment]
Hi @thecrypticace 

I think is something to do with `vue-style-loader` based on: [this](https://github.com/vuejs/vue-web-component-wrapper/issues/12#issuecomment-385141573) and this [this](https://stackoverflow.com/questions/53431754/styling-not-applied-to-vue-web-component-during-development)


I tried to override mix config for `.scss` with:

`javascript
module: {
		  	rules: [
		  		{
			        test: /\.s(c|a)ss$/,
			        use: [
			          	{
			            	loader: 'vue-style-loader',
			            	options: {
			              		shadowMode: true
			            	}
			          	},
			          	'css-loader',
          				{
					      	loader: 'sass-loader',
		                    options: {
		                        sassOptions: {
		                            precision: 8,
		                            outputStyle: 'expanded',
		                            indentedSyntax: true
		                        }
		                    }
					    }
			        ]
		 	 	}
		  	]
	  	}
`

But no success.

**Comment by Froxz** [comment]
Hi @thecrypticace 

Closing this, downgrading `css-loader` to v3 fixes this issue see: [PR](https://github.com/vuejs/vue-style-loader/pull/47)

**Comment by thecrypticace** [comment]
I was playing around with this a while ago myself and couldn't get shadowMode to work properly under any circumstance. Additionally we've had some problems with vue-style-loader necessitating reverting that change.

**Comment by Froxz** [comment]
Hi @thecrypticace I used this with Vue Webcomponents and works fine: https://github.com/vuejs/vue-web-component-wrapper

**Comment by Froxz** [comment]
Hi @thecrypticace 

With latest release I see you have added, option to choose between `vue-style-loader` and `style-loader` [v6.0.25](https://github.com/JeffreyWay/laravel-mix/blob/v6.0.25/src/components/CssWebpackConfig.js#L189)

But, by default shadow mode in `vue-style-loader` is disabled, can we add a posibility to pass options to `vue-style-loader`


```js
.vue({
	version: 2,
	runtimeOnly: true,
	useVueStyleLoader: true,
	vueStyleLoaderOptions: {
		shadowMode: true
		//or other vue-style-loader options
		// Like manualInject or ssrId  and etc
	}
})
```
