### ISSUE TITLE
Laravel Mix with Typescript standard web-component

### ISSUE THREAD

**Issue by stefanhuber** [laravel-mix/laravel-mix#2674]
-   Laravel Mix Version: 5.0.9 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.15.0
-   NPM Version (`npm -v`): 6.14.5
-   OS: Windows 10

### Description:

I use laravel mix with typescript and tried to built a simple and standard web-component.

![grafik](https://user-images.githubusercontent.com/5379359/102269264-ae400f00-3f1c-11eb-89cf-6dd6900ee718.png)

#### webpack.mix.js

```json
const mix = require('laravel-mix');
mix.ts('resources/ts/category.ts', 'public/js');
```

#### resources/ts/category.ts

```typescript
class CategoryButton extends HTMLElement {
    constructor() {
        super();
    }
}

window.customElements.define('my-category-button', CategoryButton);
```

#### ìnside blade template

```html
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel</title>
    <script src="js/category.js"></script>
  </head>
  <body>
  </body
</html>
```

**Comment by thierrydev** [comment]
[You did not actually call the custom element.](https://www.webcomponents.org/introduction#how-do-i-use-a-web-component-)

I recommend making web components without Typescript first to understand their lifecycle.

**Comment by thecrypticace** [comment]
This is due to a webpack compiling issue when targeting ES5. Try using Mix v6 & typescript + tsconfig with a target of ES2015 or greater. I've used custom elements in this case and it worked perfectly.
