### ISSUE TITLE
url reference for package static assets is broken in v6

### ISSUE THREAD

**Issue by ctf0** [laravel-mix/laravel-mix#2709]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`) 6.0.3
-   Node Version (`node -v`): v15.4.0
-   NPM Version (`npm -v`): 6.14.9
-   OS: osx 10.15.7

### Description:

i have a package that load static assets "svg file" based on conditions [ex](https://github.com/ctf0/vue-notif/blob/96e28105de07ebb9bc78cd1ee741dd4063f81ff9/src/Notification.vue#L256)
however even that the files are being copied to `public` ex.`public/images/vendor/vue-notif/src/icons/baseline-check_circle-24px.svg` 
the url is not correctly referenced as it used to in v5 & instead am getting `http://demos.test/[object%20Module]`

### Steps To Reproduce:

- install https://github.com/ctf0/vue-notif
- follow the rdme for usage
- check console

**Comment by Ragash** [comment]
See this, probably related.
https://github.com/JeffreyWay/laravel-mix/issues

**Comment by thecrypticace** [comment]
@ctf0 Can you update to the latest patch release and see if this is fixed for you?

**Comment by ctf0** [comment]
@thecrypticace after the last patch, am now start to get `Uncaught TypeError: Vue is not a constructor`

**Comment by thecrypticace** [comment]
What version of Vue are you using? If you're using Vue 3 you should import and use `createApp` instead of `new Vue()`

**Comment by ctf0** [comment]
am still on version 2

**Comment by ctf0** [comment]
**v6.0.11** still not working

**Comment by thecrypticace** [comment]
We use the ESM build Vue in all cases. Use `const Vue = require('vue').default` or use ES Imports: `import Vue from "vue"`

**Comment by ctf0** [comment]
oh ok, got it fixed now, however the main issue still exist

`http://demos.test/[object%20Module]`, any thoughts ?

**Comment by thecrypticace** [comment]
Ah okay, this is an issue with file-loader + vue-loader. `file-loader` uses ES Modules by default now and vue-loader doesn't detect that. It should really be fixed on vue-loader's side but we might need a way to turn that off in the mean time.

**Comment by ctf0** [comment]
sadly nothing new with the latest version `0.19`, issue still exist
