### ISSUE TITLE
Event hooks not running when watching

### ISSUE THREAD

**Issue by Propaganistas** [laravel-mix/laravel-mix#2812]
Thanks a bunch for the newly introduced `before()` and `after()` event hooks. They'll result in a much terser (pun) mix definitions file.

In case of "watching" for file changes, I'm observing that the `before()` hook only runs in the initial compilation. Subsequent compilations because of file changes don't seem to trigger that hook anymore.

Is this expected? If so, are there any alternatives to achieve such functionality?

**Comment by thecrypticace** [comment]
@JeffreyWay Was the intention to run before() hooks on each build or just once before everything? Could we change the behavior and consider it a bug fix or should we introduce a new event hook (beforeEachBuild or something like that)?

For reference the mix.after hook runs after each build but the mix.before hook runs once before the first build.

**Comment by JeffreyWay** [comment]
Yeah, `before()` was always intended to run once at the very beginning. 

@Propaganistas What's the use case for a before hook that runs after every watch recompilation?

**Comment by Propaganistas** [comment]
@JeffreyWay

I'm using MDI icons and have created a Vue icon component that accepts a string name to render the icon.
The icon component fetches the svg path data for the icon using a dynamic `require()` statement. Something like `require('@mdi/js')[icon]`.

Yet this approach will always include the full icon set in the compiled bundle, which is rather cumbersome given the size of the icon set.

MDI supports tree shaking, but only when named exports are used (`import { mdiHome } from '@mdi/js'`), which in turn cannot be expressed in a dynamic way. So I figured to use Mix' `before()` hook to find all occurences of my Icon component, extract the icon names, and then create a so-called library file.

This is the last part of my `before()` hook:

```js
fs.writeFileSync(path.join(__dirname, 'resources/js/icons.library.js'),
    `export {\n` + icons.join(`,\n`) + `\n} from '@mdi/js'`,
)
```

and my Icon component now references `icons.library.js` instead of `@mdi/js`.

It's actually working great. I now have explicit, tree-shaken named imports for all of the actual used icons by just referencing them by name, without ever thinking of managing the import list manually.

I think my use case for having that library file updated in each build becomes quite clear?

**Comment by Propaganistas** [comment]
I think the case remains valid.

**Comment by thecrypticace** [comment]
If we add support for this it'll be in a separate call. `mix.before` runs before the build is even set up so it's not the appropriate place. In the interim you can achieve this with a custom webpack plugin using the `beforeCompile` hook
