### ISSUE TITLE
Warrning when watching You are running the esm-bundler build of Vue...

### ISSUE THREAD

**Issue by RomkaLTU** [laravel-mix/laravel-mix#2905]
-   Laravel Mix Version: 6.0.13
-   Node Version (`node -v`): v14.15.5
-   NPM Version (`npm -v`): 6.14.11
-   OS: OSX BigSur

### Description:

Should I care about this warning when running npm run watch?

```
You are running the esm-bundler build of Vue. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
```

Not quite sure what it telling me. This message is;t visible on the production build but still want to get rid of it.

**Comment by thecrypticace** [comment]
Oh, right yeah we should set the necessary defines when using `.vue()` and Vue 3. Good catch.

**Comment by nicolailebek** [comment]
Here's how you get rid of it
```
mix.js("resources/js/app.js", "public/js")
    .vue({ version: 3 })
    .webpackConfig((webpack) => {
        return {
            plugins: [
                new webpack.DefinePlugin({
                    __VUE_OPTIONS_API__: true,
                    __VUE_PROD_DEVTOOLS__: false,
                }),
            ],
        };
    })
```

**Comment by keithbrink** [comment]
This is not stale, just low priority.

**Comment by noogen** [comment]
Just found nicolailebek recommendation also fix **__VUE_PROD_DEVTOOLS__** error in production.

**Comment by Alhiane** [comment]
@nicolailebek  very helpful for laravel mix

**Comment by cweiske** [comment]
[This configuration](https://github.com/laravel-mix/laravel-mix/issues/2905#issuecomment-815544991) also helps against the following warning:

> Feature flag \_\_VUE_PROD_HYDRATION_MISMATCH_DETAILS\_\_ is not explicitly defined. You are running the esm-bundler build of Vue, which expects these compile-time feature flags to be globally injected via the bundler config in order to get better tree-shaking in the production bundle.
> 
> For more details, see https://link.vuejs.org/feature-flags.

```
mix.js('resources/js/app.js', 'public/js')
   .vue()
   .webpackConfig((webpack) => {
       return {
           plugins: [
               new webpack.DefinePlugin({
                   __VUE_OPTIONS_API__: true,
                   __VUE_PROD_DEVTOOLS__: false,
                   __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: false,
               }),
           ],
       };
   })
```
