### ISSUE TITLE
Combine only sometimes does its job

### ISSUE THREAD

**Issue by binarweb** [laravel-mix/laravel-mix#2907]
-   Laravel Mix Version: 6.0.13
-   Node Version: v14.16.0
-   NPM Version: 6.14.11
-   OS: Windows 10

### Description:

I must be doing something wrong, because the order of operations is **most of the time** not kept.

`webpack.mix.js` content:

```js
const mix = require('laravel-mix');
const del = require('del');

mix.sass('font.scss', 'font.css');
mix.sass('login.scss', 'temp-login.css');
mix.combine(['font.css', 'temp-login.css'], 'login.css').after(function() {
    del('font.css');
    del('temp-login.css');
});
```

The output:

> ✔ Compiled Successfully in 2561ms
> ┌───────────────────────────────────┬──────────┐
> │                              File │ Size     │
> ├───────────────────────────────────┼──────────┤
> │                      login.css │ 0 bytes  │
> │                       font.css │ 1.13 KiB │
> │            temp-login.css │ 129 KiB  │
> └───────────────────────────────────┴──────────┘

As you an see, this time the `login.css` file has zero bytes.

### Steps To Reproduce:

see above

**Comment by maiconmva** [comment]
same problem here!!

**Comment by JackWH** [comment]
This is still an issue in v6.0.13, so should be re-opened. 

It can be bypassed by calling `yarn run production` (or equivalent) _twice_, but that's obviously not ideal for deployment speeds.
