### ISSUE TITLE
Use Asset Modules over file-loader

### ISSUE THREAD

**Issue by strarsis** [laravel-mix/laravel-mix#2914]
According to the webpack 5 documentation the `file-loader` should be replaced by the [asset module](https://webpack.js.org/guides/asset-modules/).
Laravel mix still uses the `file-loader` instead. Would it be a good idea to replace it then?

**Comment by thecrypticace** [comment]
Wow I completely missed this one during the upgrade process. Thanks for pointing this out. This is definitely something we should look into. I don't know if we could do it in a backwards compatible manner but perhaps offer a way to use the new asset stuff instead of file loader.

**Comment by strarsis** [comment]
Not stale.
