### ISSUE TITLE
Add avif to globs

### ISSUE THREAD

**Issue by strarsis** [laravel-mix/laravel-mix#2916]
The imagefile-related globs already contain `webp`. `avif` support becoming better and it would make sense to add the `avif` format to the globs, too.

**Comment by thecrypticace** [comment]
Agreed! I've started using avif in some projects within the past few months. This would definitely be a good addition.

**Comment by strarsis** [comment]
Note stlae.

**Comment by thecrypticace** [comment]
Merged into master
