### ISSUE TITLE
npm run dev suddenly not working anymore. VueLoaderPlugin issue

### ISSUE THREAD

**Issue by redbeavermedia** [laravel-mix/laravel-mix#2976]
-   Laravel Mix Version: 6.0.19 (`npm list --depth=0`)
-   Node Version (`node -v`): 15.2.1
-   NPM Version (`npm -v`): 7.13.0
-   OS: Mac BigSur 11.2.1
-   VueLoaderPlugin: 7.13.0

### Description:

When running npm run dev I can't get behind this error.
Going crazy because already searching for 1 day to solve this error, but don't know how.
Somebody issuing the same error after npm install a component?

> [webpack-cli] TypeError: VueLoaderPlugin is not a constructor
>     at Vue.webpackPlugins (/Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/components/Vue.js:116:17)
>     at ComponentRegistrar.applyPlugins (/Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/components/ComponentRegistrar.js:203:23)
>     at /Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/components/ComponentRegistrar.js:102:50
>     at /Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/Dispatcher.js:37:62
>     at Array.map (<anonymous>)
>     at Dispatcher.fire (/Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/Dispatcher.js:37:47)
>     at Mix.dispatch (/Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/Mix.js:244:32)
>     at WebpackConfig.buildPlugins (/Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/builder/WebpackConfig.js:176:24)
>     at WebpackConfig.build (/Users/maarenlermytte/Documents/crm/node_modules/laravel-mix/src/builder/WebpackConfig.js:31:20)
>     at async /Users/maarenlermytte/Documents/crm/node_modules/webpack-cli/lib/webpack-cli.js:1391:37

**Comment by w99910** [comment]
I'm also facing the same issue too.

**Comment by redbeavermedia** [comment]
Fixed it by running the following commands:

npm install vue-loader@^15.9.5 --save-dev --legacy-peer-dep
npm install laravel-mix@latest
npm cache clean --force
npm install && npm run dev

**Comment by thecrypticace** [comment]
Closing as you fixed the issue. The npm cache is a bit weird sometimes.
