### ISSUE TITLE
Extend Laravel Mix object

### ISSUE THREAD

**Issue by bram-pkg** [laravel-mix/laravel-mix#2996]
Hi, I am trying to extend the Laravel Mix object with custom types using a `d.ts` file. Do you have any idea why this would not offer autocompletion in VS Code and PhpStorm?

![image](https://user-images.githubusercontent.com/13304739/120833798-809a6100-c562-11eb-84a5-f38a83e95192.png)

```ts
declare namespace mix {
  export interface Api {
    /** Enable SRI integrity hash generation. */
    generateIntegrityHash(options?: Options): mix.Api
  }
}
```

**Comment by thecrypticace** [comment]
This was addressed back in May. There is another update to the types to fix usage in common JS deps that we'll be releasing soon but it won't change what you have to do.

You should do the following:

```ts
declare module 'laravel-mix' {
  export interface Api {
    /** Enable SRI integrity hash generation. */
    generateIntegrityHash(options?: Options): mix.Api
  }
}
```
