### ISSUE TITLE
Critical cssnano vulnerabilities 

### ISSUE THREAD

**Issue by bkupps23** [laravel-mix/laravel-mix#3002]
Laravel Mix Version: 6.0.19 (npm list --depth=0)
Node Version (node -v): v12.16.2
NPM Version (npm -v): 7.13.0

### Description: Recently i upgraded laravel mix to 6.0.19 and when i do a security check it is showing 2 high vulnerabilities.As vulnerable packages(packages related to cssnano package)are peer dependencies to laravel  mix i can not update them directly . 
When i checked this https://github.com/JeffreyWay/laravel-mix page is with latest `cssnano`  but when i try to update Laravel Mix it is not getting updated. 
Any alternative for this((my project is dockerized and pipe is lined with security check due to this i can not do any further deployed) )??

**Comment by kranthiboga23** [comment]
@thecrypticace Can we get any alternative on this??

**Comment by thecrypticace** [comment]
I've been incredibly busy — apologies. I've got one thing to take a look at before we can tag a new release to be sure there isn't a regression. I'll make a note to take a look at that this weekend.

**Comment by range-of-motion** [comment]
I'm still getting the vulnerability through `nom audit`. Does that mean that the recently tagged v6.0.20 did not intend to fix this?

**Comment by MariellevDijk** [comment]
The problem is coming from @types/browser-sync, that requires an old version of chokidar (2.1.8)

**Comment by skeemer** [comment]
Here's a link to an issue regarding this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/52678

**Comment by thecrypticace** [comment]
The browser-sync issue has been fixed. We pulled the types in directly to bypass the chokidar problem. There's gotta be a better solution though. :/
