### ISSUE TITLE
Error in PostCSS Loader requires full restart

### ISSUE THREAD

**Issue by DarkGhostHunter** [laravel-mix/laravel-mix#3020]
-   Laravel Mix Version: @master
-   Node Version (`node -v`): v14.16.0
-   NPM Version (`npm -v`): v6.14.11
-   OS: Windows 10 21H1

### Description:

Using `mix watch`, before Tailwind 2.2, any error parsing CSS `@apply` directive can be recovered by updating the offending CSS code.

```
.something {
    @apply this-is-invalid-pls-help-cuz-mix-went-awol;
}
```

The above will spawn an error:

```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

<css input> The `this-is-invalid-pls-help-cuz-mix-went-awol` class does not exist. If `this-is-invalid-pls-help-cuz-mix-went-awol` is a custom class, make sure it is
defined within a `@layer` directive.
    at processResult (\projects\example\node_modules\webpack\lib\NormalModule.js:701:19)
    at \projects\example\node_modules\webpack\lib\NormalModule.js:807:5
    at \projects\example\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at \projects\example\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (\projects\example\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (\projects\example\node_modules\postcss-loader\dist\index.js:140:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

Now, the error will still spawn, but further updates won't rebuild the CSS, requiring a full Laravel Mix restart to continue.

> This uses Tailwind 2.2 JIT engine.

### Steps To Reproduce:

1. [Download the repository](https://github.com/DarkGhostHunter/tailwindbug)
2. Update Laravel Mix to latest: `npm install git://github.com/JeffreyWay/laravel-mix.git#master --save -D`.
3. Change any CSS with an invalid component name.

**Comment by JeffreyWay** [comment]
Okay, so I just updated my own codebase to the Mix 6.0.24 and Tailwind 2.2. I can't reproduce what you're seeing. If I add an error to the `@apply` call, it doesn't kill the watcher. As soon as I fix the error, it re-compiles immediately.

**Comment by DarkGhostHunter** [comment]
I figured it out. It happens but inside an @import'ed file.

If the entrypoint is `app.css`, it will be fixed.

```postcss
@import "something.css"

p {
    /* @apply invalid; */
    @apply hidden;
}
```

But inside an import, it doesn't work, and it doesn't compile again on file change.

```postcss
/* something.css

p {
    /* @apply invalid; */
    @apply hidden;
}
```

Mystically, BrowserSync picks ups the changes.

**Comment by DarkGhostHunter** [comment]
Do you require more details on this? Having to restart Laravel Mix for every typo substracts time from active development.

**Comment by thecrypticace** [comment]
I'm planning to look into this but I won't have time until mid-to-late next week.

**Comment by JeffreyWay** [comment]
I still haven't been able to reproduce this on my end. Even when the code is within an import, errors are properly handled without the watcher failing. 

I'm curious what's causing this.

**Comment by DarkGhostHunter** [comment]
I'm on Windows, and running the script through yarn via PHPStorm.

**Comment by daugaard47** [comment]
I'm having a very similar issue:
[https://github.com/tailwindlabs/tailwindcss/issues/4712#issuecomment-877004319](https://github.com/tailwindlabs/tailwindcss/issues/4712#issuecomment-877004319)
