### ISSUE TITLE
Sourcemaps are active, but no output?

### ISSUE THREAD

**Issue by EquineOntology** [laravel-mix/laravel-mix#3029]
-   Laravel Mix Version (`npm list --depth=0`): 6.0.25 
-   Node Version (`node -v`): 14.17.1
-   NPM Version (`npm -v`): 6.14.13
-   OS: macOS Big Sur (11.4)

### Description:
Hi folks!

I'm not a habitual user of mix so this might be a misunderstanding on my part, please bear with me.
I'm migrating a legacy SPA (PHP + JS, JS previously minified & concatenated with gulp) to Laravel, and I'm currently stuck on sourcemap generation - they just don't seem to appear?

# How to reproduce
I feel like the issue might be more about something I'm doing rather than a bug, but here goes:

Here are the relevant parts of my `webpack.mix.js` file, I omitted all path arrays but I can assure you that everything is compiling correctly - the problem is **only** that I can't find sourcemaps anywhere. 
As a side note, I am perfectly aware that the current setup is not optimal, but my objective is to first get the app working with as few changes as possible from the base (which means creating a bunch of different bundles), and only then start on improvements and optimizations.

**webpack.mix.js**:
``` javascript
mix.disableNotifications();
mix.options({processCssUrls: false});

mix.babel([files], 'public/js/ie11polyfills.js')
	.babel([files], 'public/js/libs1.js')
	.babel([files], 'public/js/app.js')
	.babel([files], 'public/js/webrtc-controller.js')
	.babel([files], 'public/js/ie11polyfills3.js')
	.babel([files], 'public/js/ie11polyfills2.js')
	.babel([files], 'public/js/tracking.js')
	.combine([files], 'public/js/libs2.js')
	.combine([files], 'public/js/vendor.js')
	.combine([files], 'public/js/end_of_body.js')
	.combine([files], 'public/js/linkify.js')
	.copy('resources/js/libs/XRControllerModelFactory.js', 'public/js/XRControllerModelFactory.js')
	.copy('resources/js/libs/mcm.js', 'public/js/mcm.js')
	.styles([files], 'public/css/app.css')
	.sourceMaps()
	.version();
```

I have already checked the documentation I could find on sourcemaps, specifically:
- https://laravel-mix.com/docs/6.0/examples#enable-source-maps
- https://laravel-mix.com/docs/6.0/api#sourcemapsgenerateforproduction-devtype-productiontype
- https://laravel-mix.com/docs/6.0/quick-webpack-configuration combined with https://webpack.js.org/configuration/devtool/
- The typescript documentation of `.sourceMaps()` in the IDE, which just says "Generate source maps" as you'd kinda expect

And I have tried the following configurations (not together obviously), with both `npm run dev` (i.e. `mix`) and `npm run prod` (i.e. `mix --production`):
```
.sourceMaps()
.sourceMaps(true)
.sourceMaps(false)
.sourceMaps(true, 'eval-source-map', 'source-map')
.sourceMaps(true, 'source-map', 'source-map')
.sourceMaps(true, 'eval-source-map', 'eval-source-map')
```

Now, I can see that the sourcemaps setting is taken into account:
![image](https://user-images.githubusercontent.com/1936168/124714919-a79dd700-df02-11eb-8185-5c75525c67c8.png)

And Mix always compiles as expected:
![image](https://user-images.githubusercontent.com/1936168/124714729-6b6a7680-df02-11eb-8c8a-39d180f6bed5.png)

But I see no sourcemap comments in the files, and I can't find any `.map` files either.

Running `npm run prod --verbose` doesn't report much beside an apparent permissions issue that seems irrelevant to the problem at hand, since mix compilation is running fine and producing output files
![image](https://user-images.githubusercontent.com/1936168/124716653-9f469b80-df04-11eb-9933-07f4adf2869d.png)

Any help or guidance would be appreciated - am I misunderstanding something basic about how sourcemaps are generated with mix/webpack?

**Comment by toszcze** [comment]
Same issue here, the only difference is that I'm on macOS Catalina (10.15.7).

**webpack.mix.js**
```
const mix = require('laravel-mix');
require('laravel-mix-eslint');

mix.js('resources/js/app.js', 'public/js')
  .react()
  .sass('resources/sass/app.scss', 'public/css')
  .options({
    processCssUrls: false,
  })
  .extract()
  .sourceMaps();

mix.eslint({
  fix: false,
  extensions: ['js'],
  emitError: true,
  emitWarning: true,
  failOnError: true,
  formatter: 'codeframe',
});

if (mix.inProduction()) {
  mix.version();
}
```

**Comment by EquineOntology** [comment]
I haven't been able to find a solution to the issue, so for the time being I've downgraded to mix 5 which (happily for me 😄)  is creating a sourcemap without any changes to `webpack.mix.js`

**Comment by toszcze** [comment]
@EquineOntology I found a workaround. I just moved `sourceMaps()`, so now my file looks like this:
```javascript
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
  .react()
  .sass('resources/sass/app.scss', 'public/css')
  .options({
    processCssUrls: false,
  })
  .extract();

if (!mix.inProduction()) {
  mix.webpackConfig({
    devtool: 'source-map',
  }).sourceMaps();
}

if (mix.inProduction()) {
  mix.version();
}
```

**Comment by EquineOntology** [comment]
> @EquineOntology I found a workaround. I just moved `sourceMaps()`, so now my `webpack.mix.js` looks like this:
> 
> ```js
> if (!mix.inProduction()) {
>   mix.webpackConfig({
>     devtool: 'source-map',
>   }).sourceMaps();
> }
> ```

Thank you for the suggestion! I just tested it (on mix 6 of course) and it doesn't change anything for me :( 

As a note in case this issue gets reviewed by the team, every time I run these I am checking whether a map file is generated (and the sourcemap comment added) as well as whether a sourcemap was inlined within the output files

**Comment by iamacarpet** [comment]
So, it's less than ideal, but if you ever need `.babel()` to output source maps that survive through the final minify, I managed to monkey patch it like this:

```js
const Concat = require('concat-with-sourcemaps');
const babel = require('@babel/core');
const fs = require('fs-extra');
const Terser = require('terser');
const File = require('laravel-mix/src/File');
const FileCollection = require('laravel-mix/src/FileCollection');
const ConcatenateFilesTask = require('laravel-mix/src/tasks/ConcatenateFilesTask');
const { FileGlob } = require('laravel-mix/src/tasks/FileGlob');

// --- Monkey-patching Part 1: FileCollection.merge --- //

/**
 * Override the merge method to properly handle Babel source maps.
 *
 * @param {File} output
 * @param {boolean} wantsBabel
 * @returns {Promise<File[]>} A promise that resolves with an array of all generated File objects.
 */
FileCollection.prototype.merge = async function (output, wantsBabel = false) {
    const shouldCreateSourceMap =
        wantsBabel && !!this.mix.config.sourcemaps && output.extension() === '.js';

    output.makeDirectories();

    const concatenator = new Concat(
        shouldCreateSourceMap,
        output.path(),
        '\n'
    );

    for (const file of this.files) {
        const content = fs.readFileSync(file, 'utf8');

        if (this.shouldCompileWithBabel(wantsBabel, output)) {
            const babelConfig = { ...this.mix.config.babel() };
            delete babelConfig.cacheDirectory;

            const result = babel.transformSync(content, {
                ...babelConfig,
                sourceMaps: shouldCreateSourceMap,
                sourceFileName: file
            });

            if (result && result.code) {
                concatenator.add(
                    file,
                    result.code,
                    result.map ? JSON.stringify(result.map) : undefined
                );
            }
        } else {
            concatenator.add(file, content);
        }
    }

    let finalContent = concatenator.content;
    const assets = [output];

    if (shouldCreateSourceMap && concatenator.sourceMap) {
        const mapPath = output.path() + '.map';
        fs.outputFileSync(mapPath, concatenator.sourceMap);
        finalContent += `\n//# sourceMappingURL=${output.name()}.map`;
        assets.push(new File(mapPath));
    }

    fs.outputFileSync(output.path(), finalContent);
    return Promise.resolve(assets);
};

// --- Monkey-patching Part 2: ConcatenateFilesTask.merge --- //

/**
 * Override the task's merge method to handle an array of assets.
 */
ConcatenateFilesTask.prototype.merge = async function () {
    const files = await FileGlob.expand(this.data.src, {
        ignore: this.data.ignore || []
    });

    this.files = new FileCollection(files);

    // Our patched merge now returns an array of all generated files.
    const newAssets = await this.files.merge(
        this.data.output,
        this.data.babel
    );

    // Add all new assets to the task's asset list using the spread operator.
    this.assets.push(...newAssets);
};

// --- Monkey-patching Part 3: File.minify --- //

/**
 * Store original methods before patching
 */
const originalFileMinify = File.prototype.minify;

/**
 * Make the MINIFY step source-map-aware
 */
File.prototype.minify = async function () {
    // If this isn't a JS file, use the original method.
    if (this.extension() !== '.js') {
        return originalFileMinify.apply(this, arguments);
    }

    const mapPath = this.path() + '.map';
    const sourceMapContent = fs.existsSync(mapPath)
        ? fs.readFileSync(mapPath, 'utf8')
        : null;

    // If there's no source map, there's nothing to chain.
    // This can happen for non-babel() JS files.
    if (!sourceMapContent) {
        return originalFileMinify.apply(this, arguments);
    }

    // Configure Terser to use our existing source map as input.
    const config = {
        ...this.mix.config.terser.terserOptions,
        sourceMap: {
            content: sourceMapContent,
            url: `${this.name()}.map`
        }
    };

    const output = await Terser.minify(this.read(), config);

    if (output.code !== undefined) {
        // Overwrite the original JS file with the minified code.
        this.write(output.code);

        // Overwrite the original .map file with the new, correct map.
        if (output.map) {
            fs.outputFileSync(mapPath, output.map);
        }
    }

    return this;
};

// --- Our original webpack.mix.js file starts here --- //

var mix = require('laravel-mix'),
    config = require('./mix-config');

...
```

This was necessary as we needed the source maps for a legacy application, but, switching from `.babel()` to `.js()` changed the variable scope from global to self-contained modules, which broke a lot of the JavaScript on this application.
