### ISSUE TITLE
Unable to set specific webpack devserver options

### ISSUE THREAD

**Issue by BARNZ** [laravel-mix/laravel-mix#3040]
-   Laravel Mix Version: laravel-mix@6.0.25
-   Node Version (`node -v`): 12.16.1
-   NPM Version (`npm -v`): 6.13.4
-   OS: Windows 10

### Description:

Wanting to configure the following webpack devserver `clientLogLevel` and `stats` options as documented here:
https://webpack.js.org/configuration/dev-server/#devserverclientloglevel

I would have thought it should just be a matter of adding this in laravel mix:

```js
mix.webpackConfig({
    devServer: {
        clientLogLevel: 'warn',
        stats: 'errors-only'
    }
})
```

Have also tried using the `mix.override` apporach:

```js
mix.override(webpackConfig => {
    webpackConfig.devServer.clientLogLevel = 'error'
    webpackConfig.devServer.stats = 'errors-only'
})
```

However with either option added I get the following error:

`yarn hot`

![image](https://user-images.githubusercontent.com/2202345/126081761-736127c7-2f50-4ba7-bedb-5593d3b490da.png)

**Comment by henriquecm** [comment]
I have same problem, even if a separated webpack.config.js file

**Comment by te1** [comment]
I have the same problem with `clientLogLevel` and `overlay`. The code below used to work fine with Mix 5.0.4 but now after upgrading to Mix 6.0.27 I get the same error as above (using npm, not yarn).

```js
mix.webpackConfig({
  devServer: {
    overlay: true,
    clientLogLevel: 'error',
  }
});
```

- Laravel Mix Version: laravel-mix@6.0.27
- Node Version (`node -v`): 14.16.1
- NPM Version (`npm -v`): 6.14.12
- OS: Windows 10

**Comment by thecrypticace** [comment]
We're using a newer version of webpack-dev-server. These options have been renamed but the documentation was not yet updated when this issue was opened. I recommend checking the dev server documentation now as it _should_ be updated. We'll have another release coming out soon that upgrades to the latest tagged version of webpack dev server.
