### ISSUE TITLE
Catch file not found

### ISSUE THREAD

**Issue by vodnicearv** [laravel-mix/laravel-mix#3052]
-   Laravel Mix Version: 6.0.10
-   Node Version: 14.15.4
-   NPM Version: 6.14.11
-   OS: Windows

### Description: 
when file is not found, need to show an error, but debug of this is missing

### Steps To Reproduce:
in webpack.mix.js write:
`mix.styles(['resources/css/undefined-file.css'], 'public/css/test.css');`

**Comment by Cadeniuc** [comment]
I have the same error...
