### ISSUE TITLE
Hot module reload is not refreshing the browser

### ISSUE THREAD

**Issue by AhmadOf** [laravel-mix/laravel-mix#3074]
-   Laravel Mix Version: 6.0.28
-   Node Version: v14.17.2
-   NPM Version: 6.14.13
- YARN Version: 1.22.11
-   OS: Linux Ubuntu 20.04

### Description:
After upgrading to latest Laravel Mix version which is 6.0.28, I am facing an issue with hot module reload which is that any change in source code will trigger the recompilation again but the browser is not being refreshed at all and I can't see any thing in the console related to [HMR] or recompiling or anything and when I refresh manually I can see the changes applied.

Something I noticed that now I can see a lot of requests to ws://localhost:8080/ws and it is happening every 1 second constantly.

I also have a project with version 6.0.25 of Laravel Mix and it was fine with just one request to ws://localhost:8080/ws, and I upgraded it to version 6.0.28 and start getting same issue.

### Steps To Reproduce:
yarn hot

**Comment by adietz** [comment]
I was able to get HMR working again by adding this to my webpack.mix.js:

`.webpackConfig({
        devServer: {
            allowedHosts: 'all'
        },
    })`

works because in my case, the request every second  to ws: was actually erroring out with an invalid host error.   Since I use laravel valet to develop, the url of my local development site is not localhost, but a url like xyz.test.    allowing all hosts cleared up the invalid host error

**Comment by AhmadOf** [comment]
@adietz that's work fine for me, now the issue solved as I am also not using localhost but a named host like mysite.local which is exist in hosts file. but the same was working fine before updating to latest version anyway.

**Comment by thecrypticace** [comment]
I'mma re-open this. That seems like something we should add to the default config.

**Comment by matthewhutchings** [comment]
Having the same issue. 

Making changes to any vue files, NPM complies the changes but they do not show on the browser unless you stop NPM and start again.

**Comment by shtbik** [comment]
Same for me:
```
"laravel-mix": "6.0.29"
"webpack": "5.51.1"
```

@adietz thanks for the workaround
