### ISSUE TITLE
Extract your BuildOutputPlugin as an external package?

### ISSUE THREAD

**Issue by guillaumebriday** [laravel-mix/laravel-mix#3078]
### Description:

I'm currently working on [rails/webpacker](https://github.com/rails/webpacker) and I found your BuildOutputPlugin pretty neat.

I would like to change the default Webpack output too like [webpack-contrib/webpack-stylish](https://github.com/webpack-contrib/webpack-stylish) did but it's now deprecated for reasons.

Did you planned to extract your [BuildOutputPlugin](https://github.com/JeffreyWay/laravel-mix/blob/master/src/webpackPlugins/BuildOutputPlugin.js) class in a dedicated package so maybe we could use it too for Webpacker?

Thanks in advance

**Comment by thecrypticace** [comment]
There aren't any plans to do so currently but I'm not opposed to the idea. If there was a plugin that was suitable we would have used that one too.

@JeffreyWay What are your thoughts? Is this something you want to do? We could do a monorepo with multiple packages (might serve as a good way to clean up some other stuff too honestly) or I could extract it and publish it myself?

**Comment by thecrypticace** [comment]
@JeffreyWay That would be fantastic!

**Comment by thecrypticace** [comment]
@guillaumebriday I've extracted it (with some additional options) here: https://github.com/laravel-mix/webpack-build-output

It's not published yet because there are definitely some customization points that need to be added if it's going to be used by more than just Laravel Mix. Mind opening some issues there detailing what you're looking for?

I've also got some things planned that could necessitate changes to the output table for mix so I want make sure the API is good enough to handle those possible improvements.

**Comment by guillaumebriday** [comment]
Awesome! Thanks @thecrypticace 🙏 

I will try to use it in Webpacker as soon as possible!

Do you know why webpack-contrib/webpack-stylish has been archived?

**Comment by thecrypticace** [comment]
it was deprecated because a reported was _supposed_ to be moved into the cli but it looks like they just updated the stats printer in webpack 5 instead.

**Comment by thecrypticace** [comment]
Sure thing, happy to help! I'm gonna try to finish up some stuff with it over the next week or two so we can publish it and use the package in mix itself.

**Comment by guillaumebriday** [comment]
Ok it was a piece of cake using it! 🎉 

In my `package.json`:
```json
"devDependencies": {
  "webpack-build-output": "link:../webpack-build-output/dist/index.js",
}
```

Add [Webpackbar](https://github.com/unjs/webpackbar):
```bash
yarn add --dev webpackbar
```

and here is my `config/webpack/development.js`:

```js
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const { merge } = require('@rails/webpacker')
const webpackConfig = require('./base')
const { BuildOutputPlugin } = require('webpack-build-output')
const WebpackBar = require('webpackbar')

module.exports = merge(webpackConfig, {
  stats: {
    preset: 'errors-warnings'
  },
  plugins: [
    new WebpackBar({
      name: 'Webpacker'
    }),
    new BuildOutputPlugin({
      clearConsole: true,
      showRelated: true
    })
  ]
})
```

Here is the output
<img width="2560" alt="Screen Shot 2021-09-01 at 22 38 51" src="https://user-images.githubusercontent.com/8252238/131741686-79d36910-d2c7-4440-84c4-0d2eaada88e6.png">
