### ISSUE TITLE
Subdirectory is not written to the manifest

### ISSUE THREAD

**Issue by robinheidrich** [laravel-mix/laravel-mix#3085]
-   Laravel Mix Version: 6.0.29
-   Node Version (`node -v`): 16.8.0
-   NPM Version (`npm -v`): 7.21.1
-   OS: Windows 10

### Description:
I use `mix.copy()` to copy a directory and `mix.version()` above to version everything.

The subdirectory in the specified directory is copied, but not written to the manifest.

### Steps To Reproduce:
Create a directory with a subdirectory in it and use `mix.copy('path/to/directory', 'public').version()` to copy and version it.

Although the subdirectory has been copied, it is not written to the manifest.

**Comment by vasilis-exo** [comment]
I am defending the same issue! Any solution?
