### ISSUE TITLE
clean-css and cssnano, which one is used? 

### ISSUE THREAD

**Issue by florianbouvot** [laravel-mix/laravel-mix#3086]
Hi, I just saw that Mix have clean-css and cssnano as dependencies and I'm wondering witch one are used for minification/opimisation?

I try to customize cssNano config but it doesn't seems to work.

Thank you.

**Comment by thecrypticace** [comment]
CSSNano is used by webpack. For things using .styles/.combine/etc… clean-css is used. We should be using cssnano for everything. It's a historical left over that I plan to remove eventually. There's no reason to have both.

**Comment by florianbouvot** [comment]
Thank you
