### ISSUE TITLE
npm run development Mix compile error 

### ISSUE THREAD

**Issue by Chi-G** [laravel-mix/laravel-mix#3089]
-   Laravel Mix Version: #.#.# (`^6.0.6`)
-   Node Version (`14.17.0`):
-   NPM Version (`6.14.13`):
-   OS: windows 10

### Description:
├──  laravel-mix@0.11.4

npm ERR! Please include the following file with any support request:
C:\Users\chijid1\AppData\Roaming\npm-cache\_logs\2021-09-08T09_23_47_890Z-debug.log

`0 info it worked if it ends with ok`
`1 verbose cli [`
`1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]`
`2 info using npm@6.14.13`
`3 info using node@v14.17.0`
`4 verbose run-script [ 'predev', 'dev', 'postdev' ]`
`5 info lifecycle @~predev: @`
`6 info lifecycle @~dev: @`
`7 verbose lifecycle @~dev: unsafe-perm in lifecycle true`
`8 verbose lifecycle @~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\chijid1\Desktop\workspace\loggingManagementSystem\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\flutter\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\ProgramData\ComposerSetup\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\xampp\php;C:\xampp\mysql\bin;C:\Users\chijid1\AppData\Local\Microsoft\WindowsApps;C:\Users\chijid1\AppData\Local\Programs\Microsoft VS Code\bin;C:\xampp\php;C:\Users\chijid1\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\chijid1\AppData\Roaming\npm;C:\Users\chijid1\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Sublime Text 3;C:\Users\chijid1\vendor\composer;`
`9 verbose lifecycle @~dev: CWD: C:\Users\chijid1\Desktop\workspace\loggingManagementSystem`
`10 silly lifecycle @~dev: Args: [ '/d /s /c', 'npm run development' ]`
`11 silly lifecycle @~dev: Returned: code: 1  signal: null`
`12 info lifecycle @~dev: Failed to exec dev script`
`13`
`13 verbose stack Exit status 1`
`13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)`
`13 verbose stack     at EventEmitter.emit (events.js:376:20)`
`13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)`
`13 verbose stack     at ChildProcess.emit (events.js:376:20)`
`13 verbose stack     at maybeClose (internal/child_process.js:1055:16)`
`13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)`
`14 verbose pkgid @`
`15 verbose cwd C:\Users\chijid1\Desktop\workspace\loggingManagementSystem`
`16 verbose Windows_NT 10.0.19042`
`17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run"``"dev"`
`18 verbose node v14.17.0`
`19 verbose npm  v6.14.13`
`20 error code ELIFECYCLE`
`21 error errno 1`
`22 error @ dev: npm run development`
`22 error Exit status 1`
`23 error Failed at the @ dev script.`
`23 error This is probably not a problem with npm. There is likely additional logging output above.`
`24 verbose exit [ 1, true ]`

**How do i solve this problem?** when i run `npm run dev`
img 1
![Screenshot (244)](https://user-images.githubusercontent.com/35651026/132499130-35801b99-cbc4-40d8-990a-b31720b1265b.png)
img 2 cont...
![Screenshot (243)](https://user-images.githubusercontent.com/35651026/132499138-f42f31de-6f5d-4529-8d39-d30949f83563.png)

**app.scss** file below
`{`
`"private": true,`
`"scripts": {`
`"dev": "npm run development",`
`"development": "mix",`
`"watch": "mix watch",`
`"watch-poll": "mix watch -- --watch-options-poll=1000",`
`"hot": "mix watch --hot",`
`"prod": "npm run production",`
`"production": "mix --production"`
`},`

`{`
`"devDependencies":`
`"axios": "^0.21",`
`"bootstrap": "^5.1.1",`
`"laravel-mix": "^6.0.6",`
`"lodash": "^4.17.19",`
`"popper.js": "^1.16.1",`
`"postcss": "^8.1.14",`
`"resolve-url-loader": "^4.0.0",`
`"sass": "^1.39.0",`
`"sass-loader": "^12.1.0"`
`}`

**webpack.mix.js** file
`const mix = require('laravel-mix');`

`mix.js('resources/js/app.js', 'public/js');`

`mix.sass('resources/sass/app.sass', 'public/css')`
`.sass('resources/sass/admin.sass', 'public/css/admin');`

**Comment by thecrypticace** [comment]
It can't find the files with the paths given. Check the spelling and casing of the files and your paths. This is not an issue with Mix. Please ask somewhere like the Laracasts forums. Thanks!
