### ISSUE TITLE
Is there a way to add files to the manifest rather than overriding it?

### ISSUE THREAD

**Issue by Livijn** [laravel-mix/laravel-mix#3097]
I have a website and a website builder with multiple themes. I am trying to build a theme, without overriding the other ones in the `mix-manifest.json`. It would be fine if I could just stop the themes from ever touching the `mix-manifest.json` so I can just use that for the main website.

Is this possible? Or is that what you are adding in #3096 ?

**Comment by thecrypticace** [comment]
If I understand what you're asking for correctly then yes that is what we'll be adding. In the mean time you can use the `laravel-mix-merge-manifest` npm package: https://github.com/kabbouchi/laravel-mix-merge-manifest
