### ISSUE TITLE
this.files.get is not a function when combining file

### ISSUE THREAD

**Issue by ChaerilM** [laravel-mix/laravel-mix#3117]
-   Laravel Mix Version: 6.0.32 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.18.0
-   NPM Version (`npm -v`): 6.14.15
-   OS:

### Description:
I update some packages today, and seems it need node >14.17, so I installed new node and yarn. rimraf node_modules, reinstall packages, when I run watch I got these error.
### Steps To Reproduce:
```
// webpack mix

mix.styles(
    [
        "node_modules/quill/dist/quill.core.css",
        "node_modules/quill/dist/quill.snow.css"
    ],"themes/css/editor.css")

```
- yarn run watch

(node:28032) UnhandledPromiseRejectionWarning: TypeError: this.files.get is not a function
    at ConcatenateFilesTask.watch (D:\xampp\htdocs\indoconnex\node_modules\laravel-mix\src\tasks\Task.js:23:32)
    at D:\xampp\htdocs\indoconnex\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:30:57
    at Array.forEach (<anonymous>)
    at D:\xampp\htdocs\indoconnex\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:30:36
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by scriptmintsolution** [comment]
Yes, getting the same error while combining css.

**Comment by jlopes90** [comment]
+1
