### ISSUE TITLE
Webpack needs to be installed globally - Should use project installation

### ISSUE THREAD

**Issue by rredel** [laravel-mix/laravel-mix#3124]
-   Laravel Mix Version: 6.0.34
-   Node Version: 12.16.3
-   NPM Version: 6.14.4
-   OS: Windows 10

### Description:
If Webpack or Webpack-CLI is not installed globally, running `mix` fails with error `Cannot find module 'webpack-cli/package.json'` although it's present within the project's Node Modules.

### Steps To Reproduce: 

1. run `npm uninstall webpack -g`
2. run `npm i` (within the Laravel project)
3. run `npm run dev` (within the Laravel project)

-> Error: Cannot find module 'webpack-cli/package.json'

1. run `npm i webpack -g`
2. run `npm run dev` (within the Laravel project)

-> mix compiles successfully

### Expected behavior:
mix should use the project based Node Modules without requiring global packages.

**Comment by thecrypticace** [comment]
Without a reproduction there's not much I can do here. Seeing as it's not a problem with any other project I suggest poking around with the npm configs on the project you have (unless you can provide it privately so I can take a look?).

On that I'm going to close the issue but if you make more headway on a reproduction or are able to provide a the reproduction privately feel free to reopen the issue.
