### ISSUE TITLE
Hot Module Replacement is not reloading blade changes

### ISSUE THREAD

**Issue by vlados** [laravel-mix/laravel-mix#3128]
-   Laravel Mix Version: 6.0.34 (`npm list --depth=0`)
-   Node Version: v15.8.0 (`node -v`):
-   NPM Version: 7.21.1 (`npm -v`):
-   OS: MacOS 12.0 Beta (21A5534d)

### Description:
Hot Module Replacement is not reloading blade changes
### Steps To Reproduce:
1. Create a new project `laravel new laravel-mix-hot-test`
2. Install all npm packages `npm i`
3. Update npm packages to latest `npm update`
4. Start `npx mix watch --hot`
5. **Change something in `welcome.blade.php` - not reloading**
6. **Change something in `app.js` - working**

**Comment by ankurk91** [comment]
https://webpack.js.org/configuration/dev-server/#watch


Laravel-mix can watch the blade templates, which will cause dev server to reload the page
