### ISSUE TITLE
Is watch meant to re-run all tasks on all files? 

### ISSUE THREAD

**Issue by sebszocinski** [laravel-mix/laravel-mix#3150]
Not sure if this is a configuration or plugin issue but I have a project with lots of pug files which I am compiling using [laravel-mix-pug-recursive](https://github.com/mikemartin/laravel-mix-pug-recursive), and it's painfully slow at compiling... around 20 seconds every time even when just making a simple change to one pug file.

Is there any way to only compile or run the pug task on that single file that was changed?

**Comment by paul-thebaud** [comment]
Hi,
I'm having the same issue with webpack chunks, its very slow even when changing only one file from one chunk.
With Mix 5.X, changing one file creates an update in around 1sec, but with Mix 6.X, it takes around 4 to 5sec.

**Comment by sebszocinski** [comment]
hey @paul-thebaud we ended up just using [pug-cli ](https://github.com/pugjs/pug-cli) to compile pug files and left mix to just compile JS and SASS, we're seeing massive improvements but the downside is you need to have two watchers running (both mix and pug-cli watch) but you can use tools like [concurrently](https://www.npmjs.com/package/concurrently)
