### ISSUE TITLE
Disabling css minification for one file

### ISSUE THREAD

**Issue by Mushr0000m** [laravel-mix/laravel-mix#3151]
**Laravel Mix Version: 4.0.14 (but I have the same need for projects with v6)**

I use and love Mix, but I have an issue trying to disable minification for only one SASS file. This is because this file is use to style emails and some email client doesn't support minified css due to the looooong string it creates. Right now I have this : 
```
mix.sass('resources/sass/app/master.scss', 'theme/assets/app.min.css');
mix.sass('resources/sass/errors/master.scss', 'theme/assets/errors.min.css');
mix.sass('resources/sass/admin/master.scss', 'theme/assets/admin.min.css');
mix.sass('resources/sass/emails/master.scss', 'theme/assets/emails.min.css');
```
So I want to disable minification only for the line `mix.sass('resources/sass/emails/master.scss', 'theme/assets/emails.min.css')` Is this possible ?

If not is it possible to have file specific rules, maybe it's possible to create a custom `sassRaw()` extension that would do the same as `sass()` but without minification ? Or maybe an extension that would break long lines... I'm not familiar to webpack so I don't know if it's easy like it was with Gulp to create custom `task`.

Thanks for your help!

**Comment by thecrypticace** [comment]
Minification happens globally. This *may* be possible once I have time to land multiple build support but I'm not sure. I'll have to test it.

**Comment by Mushr0000m** [comment]
Thanks for your quick reply. I was afraid of that. And what about extending Mix to have a custom `breakLines()` to call like this : `mix.sass('resources/sass/emails/master.scss', 'theme/assets/emails.min.css').breakLines()` ? Is it possible with the way Mix work ?

**Comment by thecrypticace** [comment]
You can use `mix.then(async () => …)` to run code after the build has completed. Try something like this:

```js
const fs = require('fs/promises');
mix.then(async () => {
  const css = await fs.readFile('theme/assets/emails.min.css', 'utf8');
  await fs.writeFile('theme/assets/emails.min.css', css.replace(/;/g, ';\n'), 'utf8');
})
```

**Comment by Mushr0000m** [comment]
Thanks for the code it gived me a good starting point, I ended up using this (because I'm in an older version of Mix the V4) : 
```
const mix = require('laravel-mix');

mix.then(() => {
    if (mix.inProduction()) {
        const emailsCssFile = File.find('theme/assets/emails.min.css').forceFromPublic();
        const css = emailsCssFile.read(emailsCssFile);
        emailsCssFile.write(css.replace(/}/g, '}\n'));
    }
});
```
