### ISSUE TITLE
ERROR AL MOMENTO DE EJECUTAR MI MAPA LEAFLET EN MI LARAVEL

### ISSUE THREAD

**Issue by Jami-14** [laravel-mix/laravel-mix#3160]
## Buenas noches me sale este error en lo del mapa leaflet, uso el laravel 8, alguien podría decirme a que se debe? 
![ERROR 1](https://user-images.githubusercontent.com/94165690/141434198-9fe649ac-9549-48ca-8720-db05b16afd1f.PNG)
![ERROR 2](https://user-images.githubusercontent.com/94165690/141434376-6741094d-dc3d-437a-88d1-d0f346161de9.PNG)

### Si desean captura de algun codigo con gusto muestro pero espero puedan ayudarme.

**Comment by thecrypticace** [comment]
Lo siento, hace mucho que no practico mi español…
Necesita agregar `mix.vue()` a su archivo `webpack.config.js`.

> I'm sorry, I haven't practiced my Spanish in a long time…
> You need to add `mix.vue ()` to your `webpack.config.js` file.

![code](https://user-images.githubusercontent.com/614993/141474884-acbaeec5-3c29-4b71-abf1-c878d89a7782.png)
