### ISSUE TITLE
Css doesn't get compiled from powershell

### ISSUE THREAD

**Issue by mtsunu** [laravel-mix/laravel-mix#3161]
-   Laravel Mix Version: 6.0.39 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.16.1
-   NPM Version (`npm -v`): 6.14.12
-   OS: Windows 10

### Description:
On a fresh laravel breeze app.
When running `npm run prod` or `npm run dev` from powershell, the css doesn't get compiled. Only js files were compiled.
But when running it via windows command prompt the build run successfully. 

Here's my webpack.mix.js
![image](https://user-images.githubusercontent.com/4941448/141643516-3fa3ac0f-211f-432b-8888-cedce373a6ff.png)

### Steps To Reproduce:
1. install laravel + breeze
2. run `npm run prod` or `npm run dev` from powershell

**Comment by mtsunu** [comment]
It turns out this is because of symlink. Closing.

**Comment by thecrypticace** [comment]
Where was the symlink in the path? I'm curious if it's something we can detect and possibly work around or throw an error on.

**Comment by mtsunu** [comment]
The link is in `c:\Users\<username>\projects\somedir`
It points to real path `d:\projects\somedir`

When opening powershell i usually cd to the projects folder directly (from user home dir).
