### ISSUE TITLE
Feature request: Use esbuild for css and js minification

### ISSUE THREAD

**Issue by ankurk91** [laravel-mix/laravel-mix#3163]
Hi,

[esbuild](https://esbuild.github.io/) is an extremely faster alternative to [terser-js](https://github.com/terser/terser) and [css-nano](https://github.com/cssnano/cssnano)

Webpack plugins now supports esbuild officially

- [terser-webpack-plugin](https://github.com/webpack-contrib/terser-webpack-plugin/pull/426) PR
- [css-minimizer-webpack-plugin](https://github.com/webpack-contrib/css-minimizer-webpack-plugin/pull/122) PR

esbuild is stable enough and being used by many popular tools, for example:

* [vite.js](https://vitejs.dev/)
* [angular-cli](https://github.com/angular/angular-cli)
* [rails](https://github.com/rails/jsbundling-rails)
* [snowpack](https://www.snowpack.dev/posts/2021-01-13-snowpack-3-0)

esbuild can reduce memory usage and time to 50% :rocket:

esbuild can also replace babel-loader :wink:

Additional:
* https://www.npmjs.com/package/browserslist-to-esbuild
* https://www.npmjs.com/package/esbuild-loader
* [Next.js is using SWC instead of esbuild](https://nextjs.org/blog/next-11-1#adopting-rust-based-swc)

**Comment by thecrypticace** [comment]
This is definitely on my radar as a possibility. We'll have to do it in a manner that's sensible and reduces potential breakage.

For example:
1. If you can use isolated modules then there's no reason to pull in `ts-loader` if you can use something like swc or esbuild.
2. esbuild can replace terser entirely moving parsing and compilation to the optimization step. This may or may not be ideal.

**Comment by ankurk91** [comment]
I would suggest to rollout this feature gradually.

We can first use esbuild for CSS minification, tab a release, npm supports [tags](https://docs.npmjs.com/cli/v8/commands/npm-publish#tag) for publishing

```
# publish with a tag from publisher machine
npm publish --tag next

# install the tagged edition on consumer machine
npm install laravel-mix@next
```

This way; regular wont get affected by this, you can create a pinned issue "call for testing" too.

And can do the same to replace terser-js with esbuild.

**Comment by thecrypticace** [comment]
Yep, if this happens it'll be under some experimental/feature flag or something like that which requires it to be enabled.
