### ISSUE TITLE
TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by rabol** [laravel-mix/laravel-mix#3166]
-   Laravel Mix Version: 6.0.39 (`npm list --depth=0`)
-   Node Version (`node -v`): 17.0.1
-   NPM Version (`npm -v`): 8.1.0
-   OS: MacOs 11.6.1

### Description:
npm run dev failes with :
TypeError: require(...) is not a function

when building Tailwindcss and one have this:

```
plugins: [
        require('@tailwindcss/forms')({
            strategy: 'class',
        })
        
    ],
```

npm run dev fails

### Steps To Reproduce:
1) laravel new test
2) cd test
3) composer require laravel/breeze
4) php artisan breeze:install
5) npm install
6) modify taiwindcss.config.js to include the plugin as described above
7) npm run dev

observe the error

**Comment by thecrypticace** [comment]
The error is saying the _result	of	`require('@tailwindcss/forms')`_ is not a function. It's using an older version that doesn't return a function but an object of type `{ handler: Function, config: undefined }`.

Upgrade your version in package.json to `^0.3.4`.
