### ISSUE TITLE
Not adding hashes to files when Production

### ISSUE THREAD

**Issue by julesgilson** [laravel-mix/laravel-mix#3179]
-   Laravel Mix Version: 6.0.39
-   Node Version (`node -v`): 14.17.4
-   NPM Version (`npm -v`): 6.14.14
-   OS: Windows [Version 10.0.19041.1348]

### Description:
Using mix.version() is not adding the hashes to the output files when run for production. It does change the manifest though - so it points to files that don't exist... 
### Steps To Reproduce:
This is a new install of Laravel, and Vue. 
webpack.mix.js:
```
const mix = require("laravel-mix");

mix.js("resources/js/app.js", "public/js")
  .vue()
  .sourceMaps()
  .version()
  .disableSuccessNotifications();

mix.browserSync({
    proxy: "http://127.0.0.1:8000",
    host: "127.0.0.1",
    port: 3000,
    open: "external",
});

```

Tried without sourcemaps - same issue

**Comment by Krisell** [comment]
Isn't query string hashes used by default, such that the underlying referenced files are the same?

**Comment by chrisjohnstone** [comment]
I have the same issue. 

Running `sail npm run prod` builds successfully but does not append the hash to the outputted file(s).

My `mix-manifest.json` does compile correctly:

```
{
    "/js/pages/app.js": "/js/pages/app.js?id=a71bdad1243ad82d0392"
}
```

I reduced my `webpack.mix.js` down to a bare minimum:

```
let mix = require('laravel-mix');

mix.js('resources/js/pages/app.js', 'public/js/pages').version();
```

**Comment by Krisell** [comment]
@chrisjohnstone I don't quite follow – the name of the file is `app.js`, and the query string part `id=` is only used in the URL to cause browsers/servers to think the file is new. What exactly is the problem you are facing?

**Comment by julesgilson** [comment]
I think we are all talking at cross-purposes.

For some reason, in the project I was working on the other day - it was not adding hashes in the manifest but was changing the names of the files to something that does not exist...

In a different project it is fine... Probably just a corruption of something in that other project. I will close the issue.

@chrisjohnstone - what you have is the correct behaviour
