### ISSUE TITLE
Watch doesn't deliver changes when using Sass and Tailwind

### ISSUE THREAD

**Issue by lexo-mpuzovic** [laravel-mix/laravel-mix#3188]
-   Laravel Mix Version: 6.0.39 (`npm list --depth=0`)
-   Node Version (`node -v`): 17.0.1
-   NPM Version (`npm -v`): 8.1.0
-   OS: macOS Monterey v12.1

### Description:

Hi, I'm using Laravel Mix with Tailwind 3.0.7.

This is mine `webpack.mix.js` file:

```
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');

mix
  .setPublicPath('dist')
  .browserSync({
    proxy: "http://localhost:10004",
    files: [
      'dist/**/**',
      'resources/**/**',
      '**/*.php',
    ],
  });

mix
  .js('resources/scripts/app.js', 'js')
  .js('resources/scripts/admin.js', 'js')
  .js('resources/scripts/tinymce-buttons.js', 'js')
  .autoload({
    jquery: [
      '$',
      'window.jQuery',
    ],
  });

mix
  .sass('resources/styles/app.scss', 'css')
  .sass('resources/styles/admin.scss', 'css')
  .sass('resources/styles/editor.scss', 'css');

mix
  .options({
    processCssUrls: false,
    postCss:        [
      tailwindcss('./tailwind.config.js'),
    ],
  });

mix
  .copy('resources/images', 'dist/images')
  .copy('resources/fonts', 'dist/fonts');

mix
  .version()
  .sourceMaps();
```

This is the content of `tailwind.config.js` file:

```
module.exports = {
  mode:    'jit',
  content: [
    './**/*.php',
    './resources/scripts/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

### Steps To Reproduce:

Everything works fine except watch. If I use commands `npx mix build` or `npx mix --production` it builds properly everything. But if I use `npx mix watch` it starts server with port 8000 and it reloads page properly after I make some change but build is not fresh. Not only that it doesn't compile changes on Tailwind classes but also other changes in my scss files. Basically it always delivers old files created after last `npx mix build`.

If I remove this part

```
    postCss:        [
      tailwindcss('./tailwind.config.js'),
    ],
```

then all changes in scss files are properly compiled when using `npx mix watch`.

Did anyone had some problems like these? Am I doing something wrong?

**Comment by florianbouvot** [comment]
@lexo-mpuzovic it seems to be an issue in tailwindcss: https://github.com/tailwindlabs/tailwindcss/issues/4838

**Comment by JBraddockm** [comment]
I have a similar setup and the watch works as expected. In your setup, `mode:    'jit',` is no longer needed in Tailwind CSS 3.0. Your scss files are missing in your tailwind.config.js. In your webpack.mix.js, BrowserSync doesn't appear to have the correct path for scss files.

**Comment by lexo-mpuzovic** [comment]
> I have a similar setup and the watch works as expected. In your setup, `mode: 'jit',` is no longer needed in Tailwind CSS 3.0.

I know that `mode: 'jit'` is no longer needed but I was trying that in despair.

> BrowserSync doesn't appear to have the correct path for scss files.

But my SCSS files are in `resources` folder and everything compiles perfectly fine if I remove

```
postCss:        [
      tailwindcss('./tailwind.config.js'),
]
```.

> Your scss files are missing in your tailwind.config.js.

If I understood correctly, hare I need to list all files which are going to be watched. Those are files which would have Tailwind classes and based on those classes jit will do the job. And that really works for build nad production but not for watch.

**Comment by thecrypticace** [comment]
I posted information over in the issue you had opened in the tailwind repo but I'll respond here as well:

I've tried for about 15m and I'm unable to reproduce this. Browsersync refreshes and injects the CSS just as I expect. Would you mind prepping a reproduction (even if it's not quite minimal) — or at the very least more details about your setup?

**Comment by JBraddockm** [comment]
> > I have a similar setup and the watch works as expected. In your setup, `mode: 'jit',` is no longer needed in Tailwind CSS 3.0.
> 
> I know that `mode: 'jit'` is no longer needed but I was trying that in despair.
> 
> > BrowserSync doesn't appear to have the correct path for scss files.
> 
> But my SCSS files are in `resources` folder and everything compiles perfectly fine even in `watch` if I remove
> 
> ```
> postCss:        [
>       tailwindcss('./tailwind.config.js'),
> ]
> ```
> 
>  > Your scss files are missing in your tailwind.config.js.
> 
> If I understood correctly, hare I need to list all files which are going to be watched. Those are files which would have Tailwind classes and based on those classes jit will do the job. And that really works for `build` and `production` but not for `watch`.

The content[] in tailwind.config.js doesn't have scss files. You've only added js files in resources for jit to watch. In other words, Jit doesn't watch your scss files.

**Comment by florianbouvot** [comment]
Like many people, I've the same issue.

@adamwathan explain why it's not working for now: https://github.com/tailwindlabs/tailwindcss/issues/4838#issuecomment-873229081

@thecrypticace do you want a repo that reproduce this issue?

**Comment by JBraddockm** [comment]
I am aware of that specific issue. I don’t have it in my project so I can’t comment on it. However, I can see that scss files are not added to JIT watch in OP’s tailwind config, which is something I also experienced when I added files and folders to my projects but forgot to update the config file.
