### ISSUE TITLE
node-forge and postcss Vulnerabilities with Vue 2

### ISSUE THREAD

**Issue by apoorvpal01** [laravel-mix/laravel-mix#3197]
-   Laravel Mix Version: 6.0.39
-   Node Version (`node -v`): 16.6.1
-   NPM Version (`npm -v`): 8.3.0
-   OS: Windows 11

### Description:
I use VueJS 2 for my frontend and I am using laravel-mix to compile the assets. Recently, I came across a vulnerability reported by NPM regarding node-forge which is a dependency installed due to laravel-mix and one for postcss which is caused due to vue-loader < 17.0.0 . I tried upgrading to vue-loader 17.0.0 but that broke my webpack compilation. I request your help in resolving these vulnerabilities without breaking the code.

package.json
```json
"devDependencies": {
    "axios": "^0.24.0",
    "css-loader": "^6.5.1",
    "laravel-mix": "^6.0.39",
    "lodash": "^4.17.21",
    "sass": "^1.45.1",
    "sass-loader": "^12.4.0",
    "vue": "^2.6.14",
    "vue-loader": "^15.9.8",
    "vue-template-compiler": "^2.6.14"
},
```

vulnerabilities reported in `npm audit`:
```
# npm audit report

node-forge  <1.0.0
Prototype Pollution in node-forge debug API. - https://github.com/advisories/GHSA-5rrq-pxf6-6jx5
fix available via `npm audit fix --force`
Will install laravel-mix@1.1.1, which is a breaking change
node_modules/node-forge
  selfsigned  >=1.1.1
  Depends on vulnerable versions of node-forge
  node_modules/selfsigned
    webpack-dev-server  >=2.5.0
    Depends on vulnerable versions of selfsigned
    node_modules/webpack-dev-server
      laravel-mix  >=1.2.0
      Depends on vulnerable versions of webpack-dev-server
      node_modules/laravel-mix

postcss  <8.2.13
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix --force`
Will install vue-loader@17.0.0, which is a breaking change
node_modules/@vue/component-compiler-utils/node_modules/postcss
  @vue/component-compiler-utils  *
  Depends on vulnerable versions of postcss
  node_modules/@vue/component-compiler-utils
    vue-loader  15.0.0-beta.1 - 15.9.8
    Depends on vulnerable versions of @vue/component-compiler-utils
    node_modules/vue-loader
```

Error if I try to use vue-loader v17.0.0:
```
[webpack-cli] Error: Cannot find module 'vue/compiler-sfc'
```

**Comment by jeffochoa** [comment]
I'm facing the same issue, still haven't found any solution 🤔

**Comment by arborrow** [comment]
For postcss, I added a [comment](https://github.com/bholloway/resolve-url-loader/issues/198) to the impacted resolve-url-loader (4.0.0) in the hopes that they might release v5 that would upgrade postcss to a later version (currently pinned to 7.0.39).

**Comment by beatrizsmerino** [comment]
> I'm facing the same issue, still haven't found any solution 🤔

+ 1

I have the same problem. I updated the stylelint package to version 14 and now many moderate vulnerabilities appear in the postcss package.

I tried putting the `postcss` package in the resolutions object of the `package.json` file and using `npm-force-resolutions` to fix it. But that makes it worse, because although the vulnerabilities are fixed, my npm script `lint` for formatting the code stops working.

**Comment by olivsinz** [comment]
This post worked for me. I'm not using Vue, so maybe it's help me.
https://itnext.io/fixing-security-vulnerabilities-in-npm-dependencies-in-less-than-3-mins-a53af735261d

**Comment by beatrizsmerino** [comment]
its is not working for me 😞 😢

![image](https://user-images.githubusercontent.com/14045148/149402998-6e99a3c9-f9f2-4c85-8ece-1fedc4477e63.png)
![image](https://user-images.githubusercontent.com/14045148/149402891-585389df-1247-4036-8a9f-842a58a57bd2.png)
![image](https://user-images.githubusercontent.com/14045148/149403052-ad5d707a-dc90-470e-8f1c-0589ad6f9581.png)
![image](https://user-images.githubusercontent.com/14045148/149403194-2896f722-a957-4501-b5d3-3781fbf340f7.png)

**Comment by thecrypticace** [comment]
Re opening as there's still an issue re: postcss because of resolve-url loader.

**Comment by thecrypticace** [comment]
Ah they've already released a new version. I published another version of mix so it doesn't try to install 4.0. But for existing projects you can upgrade this yourself.
