### ISSUE TITLE
The `TypeScript` section of the docs, does not show up on the docs of the website

### ISSUE THREAD

**Issue by xieyuheng** [laravel-mix/laravel-mix#3202]
The `TypeScript` section of the docs: https://github.com/laravel-mix/laravel-mix/tree/master/docs

The website: https://laravel-mix.com/docs

**Comment by thecrypticace** [comment]
We do not maintain or control laravel-mix.com. It is however on GitHub. Please open an issue with them: https://github.com/mvdnbrk/laravel-mix.com
