### ISSUE TITLE
Props not working correctly with postcss compile

### ISSUE THREAD

**Issue by forestnight** [laravel-mix/laravel-mix#3213]
-   Laravel Mix Version: 6.0.41 (`npm list --depth=0`)
-   Node Version (`node -v`):14.19.0
-   NPM Version (`npm -v`):8.5.0
-   OS:Linux Mint 20.3

### Steps To Reproduce:
1. created a new laravel 9 project with breeze.
2. Changed only the button.blade.php file and the x-button component in the login.blade.php.  In the previous version of tailwind(2.x) this process worked, now the app.css file is not including the additional css from the props.
'npm run watch' is running

button.blade.php

```
@props(['color'` => 'gray'])
<button {{ $attributes->merge(['type' => 'submit', 'class' => 'inline-flex items-center px-4 py-2  border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest  focus:outline-none disabled:opacity-25 transition ease-in-out duration-150 bg-{$color}-800 hover:bg-{$color}-700 active:bg-{$color}-900 focus:border-{$color}-900 focus:ring ring-{$color}-300']) }}>
    {{ $slot }}
</button>
```

login.blade.php
```
<x-button color='blue' class="ml-3">
       {{ __('Log in') }}
</x-button>
```

**Comment by thecrypticace** [comment]
Do not use dynamic class names with Tailwind CSS. You can review the guide on that here: https://tailwindcss.com/docs/content-configuration#dynamic-class-names
