### ISSUE TITLE
npx mix adds lots of code to first js file

### ISSUE THREAD

**Issue by MaxGiting** [laravel-mix/laravel-mix#3217]
-   Laravel Mix Version: 6.0.42
-   Node Version: 14.16.0
-   NPM Version: 6.14.11
-   OS: macOS Big Sur

### Description:
I have two `.js` files and one .sass file:
`resources/src/app.js` => `alert('woop');`
`resources/src/file2.js` => `alert("I\'m file 2")`
`resources/src/styles.scss` => `.class {
    color: red;
}`

My webpack.mix.js is this
```js
// webpack.mix.js

let mix = require('laravel-mix');

mix.js('resources/src/app.js', 'dist').js('resources/src/file2.js', 'dist').sass('resources/src/styles.scss', 'dist');
```

When I run `npx mix` it moves all three files into the dist folder. But `app.js` contains a lot of extra code. `file2.js` is moves correctly. Why does `app.js` contain lots of extra code?

app.js
```js
(()=>{var r,e={830:()=>{alert("woop")},537:()=>{}},o={};function n(r){var t=o[r];if(void 0!==t)return t.exports;var a=o[r]={exports:{}};return e[r](a,a.exports,n),a.exports}n.m=e,r=[],n.O=(e,o,t,a)=>{if(!o){var v=1/0;for(p=0;p<r.length;p++){for(var[o,t,a]=r[p],i=!0,l=0;l<o.length;l++)(!1&a||v>=a)&&Object.keys(n.O).every((r=>n.O[r](o[l])))?o.splice(l--,1):(i=!1,a<v&&(v=a));if(i){r.splice(p--,1);var f=t();void 0!==f&&(e=f)}}return e}a=a||0;for(var p=r.length;p>0&&r[p-1][2]>a;p--)r[p]=r[p-1];r[p]=[o,t,a]},n.o=(r,e)=>Object.prototype.hasOwnProperty.call(r,e),(()=>{var r={532:0,363:0};n.O.j=e=>0===r[e];var e=(e,o)=>{var t,a,[v,i,l]=o,f=0;if(v.some((e=>0!==r[e]))){for(t in i)n.o(i,t)&&(n.m[t]=i[t]);if(l)var p=l(n)}for(e&&e(o);f<v.length;f++)a=v[f],n.o(r,a)&&r[a]&&r[a][0](),r[a]=0;return n.O(p)},o=self.webpackChunk=self.webpackChunk||[];o.forEach(e.bind(null,0)),o.push=e.bind(null,o.push.bind(o))})(),n.O(void 0,[363],(()=>n(830)));var t=n.O(void 0,[363],(()=>n(537)));t=n.O(t)})();
```

file2.js
```js
alert("I\'m file 2")
```

### Steps To Reproduce:

Example repo here: https://github.com/MaxGiting/Laravel-Mix-Example

**Comment by thecrypticace** [comment]
This is because the webpack runtime has to be bundled into one of the files. You can use `mix.extract()` to split out the runtime into a manifest.js file and your dependencies into a vendor.js file which is what I would recommend.
