### ISSUE TITLE
Is it possible to exclude specific entry points from the extract function?

### ISSUE THREAD

**Issue by ryuhangyeong** [laravel-mix/laravel-mix#3221]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`) 2.0
-   Node Version (`node -v`): 10
-   NPM Version (`npm -v`):
-   OS: window

### Description:

```js
let mix = require("laravel-mix");

// Extract the vendor library.
mix
  .js("src/index.js", "dist")
  .js("src/test.js", "dist")
  .vue({ version: 2 })
  .extract(["vue"])
  .version();

// It does not extract vendor libraries.
mix.js("src/noti.js", "dist").vue({ version: 2 });
```

Hello. I'm using the extract function and at the same time I don't want to use the extract function for a specific entry point. Is that possible?

**Comment by thecrypticace** [comment]
No, this is not currently possible. This could be a future enhancement — and would have to be structured differently — but this is not a typical use case for Mix. Also, a note, all `mix.*` calls are global behavior so your config is equivalent to:

```js
let mix = require("laravel-mix");

mix.js("src/index.js", "dist")
mix.js("src/test.js", "dist")
mix.js("src/noti.js", "dist")
mix.vue({ version: 2 })
mix.extract(["vue"])
mix.version()
```

**Comment by ryuhangyeong** [comment]
Thank you. your answer
