### ISSUE TITLE
GitHub Actions Docker permission denied error running mix

### ISSUE THREAD

**Issue by Jamesking56** [laravel-mix/laravel-mix#3222]
-   Laravel Mix Version: 6.0.42 (`npm list --depth=0`)
-   Node Version (`node -v`): v16.14.0
-   NPM Version (`npm -v`): 8.3.1
-   OS: Ubuntu 20.04 in Docker

### Description:

When using Laravel Mix in GitHub Actions using a Docker image with PHP + Node inside, Laravel Mix gives a permission error:

```
Run npm run production

> production
> mix --production

[info] [webpackbar] Compiling Mix
node:internal/fs/utils:344
    throw err;
    ^

Error: EACCES: permission denied, open '/__w/{SNIP}/{SNIP}/public/mix-manifest.json'
    at Object.openSync (node:fs:585:3)
    at Object.writeFileSync (node:fs:2155:35)
    at File.write (/__w/{SNIP}/{SNIP}/node_modules/laravel-mix/src/File.js:211:12)
    at Manifest.refresh (/__w/{SNIP}/{SNIP}/node_modules/laravel-mix/src/Manifest.js:86:50)
    at /__w/{SNIP}/{SNIP}/node_modules/laravel-mix/src/webpackPlugins/ManifestPlugin.js:21:48
    at Hook.eval [as callAsync] (eval at create (/__w/{SNIP}/{SNIP}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/__w/{SNIP}/{SNIP}/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (/__w/{SNIP}/{SNIP}/node_modules/webpack/lib/Compiler.js:871:19)
    at /__w/{SNIP}/{SNIP}/node_modules/webpack/lib/Compiler.js:459:10
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/__w/{SNIP}/{SNIP}/public/mix-manifest.json'
```

`npm install` works fine and can write `node_modules` fine.

### Steps To Reproduce:

I've setup a public repository that shows off the problem, here is the workflow run showing the same error message:

https://github.com/Jamesking56/mix-permissions-error/runs/5351945168?check_suite_focus=true

**Comment by trip-somers** [comment]
My team is having a similar problem. It works fine on the Docker container on my Mac host, but our Windows WSL team members are getting `/usr/bin/env: 'node': Permission denied` instead of the more verbose output you've shown. These may or may not be related problems.

**Comment by thecrypticace** [comment]
I'll be taking a look at this soon. I've run mix in GitHub Actions on a few dozen projects without issue but none of those ever used docker containers.

@trip-somers Would you mind opening a separate issue for this?

**Comment by trip-somers** [comment]
We narrowed our problem down to a Docker mounting issue. I'm going to edit-delete the previous comment.

**Comment by thecrypticace** [comment]
Ah, okay good to know. Thanks.

**Comment by Jamesking56** [comment]
@thecrypticace Feel free to play around with my public repo reproducer if you need to :+1:

**Comment by nklmilojevic** [comment]
I'm having the same problem - @Jamesking56 did you maybe research further?

**Comment by Jamesking56** [comment]
Sorry for my late reply. @trip-somers @thecrypticace @nklmilojevic 

I've got a workaround working for this just by adding a step before `npm run production`:

```yml
    - name: Fix Laravel Mix permissions issue
      run: chmod -R 0777 public
```

This is a hack at best, so this still needs fixing in some way. Not sure if its a mix bug or a GitHub actions bug if I'm honest as this bug doesn't occur when using a shared runner.

**Comment by thecrypticace** [comment]
That definitely does not seem like a Mix problem then. I don't know why the repo would be cloned with the wrong permissions but that would indeed explain why Mix could not write files to the directory. Given that I'm going to close the issue but if you run into more problems feel free to re-open it (or open a new one).

**Comment by jskorlol** [comment]
Have you ever solved this problem? I don't think it's a mix issue, it's a docker issue...
Existing projects are all fine, but new ones don't work.
Has the docker permission policy changed to be more detailed?
