### ISSUE TITLE
Infinite loop in development hot

### ISSUE THREAD

**Issue by Rasool-deldar** [laravel-mix/laravel-mix#3224]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node 16.13.2`):
-   NPM Version (`npm 8.1.2`):
-   OS: Windows

### Description:

Hello, good morning. I am using Laravel 9 and vue 2 in the new project. I encountered a problem when I use the project in hot development mode and when I put a loop inside the vuejs JavaScript code, the project inside the loop would fall indefinitely. And it does not come out, please help me to solve this problem.

### Steps To Reproduce:

```json
package.json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "axios": "^0.25",
        "laravel-mix": "^6.0.6",
        "postcss": "^8.1.14",
        "resolve-url-loader": "5.0.0",
        "sass": "~1.32.6",
        "sass-loader": "12.1.0",
        "vue-loader": "^15.9.8",
        "vue-template-compiler": "^2.6.14"
    },
    "dependencies": {
        "vue": "2.6.14"
    }
}
```
```node
// webpack.mix.js
const { resolve } = require("path");
const mix = require('laravel-mix');

mix.js('resources/scripts/main.js', 'js')
    .vue({ version: 2 })
    .copyDirectory('resources/scripts/assets/images', 'public/images')
    .alias({
        '@': resolve(__dirname, 'resources'),
        '@layouts': resolve(__dirname, 'resources/scripts/assets/vue/layouts'),
    })
    .options({
        processCssUrls: false
    })
    .extract(['vue']);
```
```node
// mian.js
import Vue from 'vue';
import App from '@layouts/Panel.vue';

const app = new Vue({
  el: '#app',
  // @ts-ignore
  render: (h) => h(App),
}).$mount('#app');

export default app;
```

Exactly the problem with adding a loop inside the vuejs JavaScript code inside the loop is infinite

```vue
Panel.vue
<template>
  <div>60000</div>
</template>

<script>
export default {
  mounted() {
    for (let i = 0; i < 3; i + 1) {
      console.log(60000);
    }
  }
};
</script>
```

**Comment by noogen** [comment]
I see error in your code here `let i = 0; i < 3; i + 1`,  did you really means `i++` or `i=i+1` instead of `i + 1`?  There's no assignment when you simply do `i+1`.

**Comment by Rasool-deldar** [comment]
> i=i+1

thanks for your help

**Comment by Rasool-deldar** [comment]
> I see error in your code here `let i = 0; i < 3; i + 1`, did you really means `i++` or `i=i+1` instead of `i + 1`? There's no assignment when you simply do `i+1`.

thanks for your help
