### ISSUE TITLE
Link issue with 6.0.43

### ISSUE THREAD

**Issue by MrJuliuss** [laravel-mix/laravel-mix#3230]
-   Laravel Mix Version: 6.0.43
-   Node Version (`node -v`): 16.2.0
-   NPM Version (`npm -v`): 8.3.1
-   OS: Ubuntu

### Description:

Hi, 

Since 6.0.43 we have an issue on app building with `npm link` feature. 
This command doesn't install linked package's dependencies. With 6.0.42 and before, it seems that *mix* retrieve the dependencies in the main `node_modules`
directory (vue in our case) but it doesn't with 6.0.43 : we have to manually `npm install` in the linked package.

I tried to check 6.0.43 modifications to see what has changed, but this released is really huged and i didn'd found why the behaviour changed.

### Steps To Reproduce:

A laravel app with a linked submodule, which have vue 3 in deps.

```
•
└── app
    └── node_modules
        ├── vue
        └── linked-package
            └── NO NODE_MODULES
```

**Comment by MrJuliuss** [comment]
Some news : 

`npm install` in linked package solved the `npm run dev` error, but now i have runtime errors : 

```
shop.js:24599 Uncaught TypeError: Cannot read properties of undefined (reading 'setBreadcrumb')

var _inject = (0,vue__WEBPACK_IMPORTED_MODULE_0__.inject)('useBreadcrumb'),
setBreadcrumb = _inject.setBreadcrumb;
```

It seems linked package vue 3 api composition is not loaded with 6.0.43 ? 

(Works very well without links)

**Comment by thecrypticace** [comment]
I'll see what I can figure out and push a release out today. Could you provide a repo or some detailed instructions on how you're using npm link? The fact that a non-linked version works but a linked version makes me think it's symlink/path resolution related but I want to be sure I can replicate your setup.
