### ISSUE TITLE
Support for Node 18

### ISSUE THREAD

**Issue by jnoordsij** [laravel-mix/laravel-mix#3249]
-   Laravel Mix Version: 6.0.43 (`npm list --depth=0`)
-   Node Version (`node -v`): 18.0.0
-   NPM Version (`npm -v`): 8.7.0
-   OS: irrelevant

### Description:
Building fails on Node v18, due to the upgrade to OpenSSL v3 (since Node 17). In #3138 and #3140 some fixes were done to ensure compatibility, but they do very specific matching on the version number.

### Steps To Reproduce:
Running test suite on Node 18 should probably be enough.

### Possible solutions:
- Simply adding an additional `process.version.startsWith('v18.')` wherever applicable (note that this means things will still break again on next Node releases)
- Doing some kind of semver-range matches on all places where Node 17 is now explicitly matched

**Comment by jnoordsij** [comment]
Note: the current issues I seem to be experiencing are related to asset hash generating by `file-loader`, which may be solved by replacing it with asset modules (see also https://github.com/laravel-mix/laravel-mix/issues/2914) and using modern `xxhash64` hashing. See https://github.com/laravel-mix/laravel-mix/issues/2914. I'm not sure if this covers all possible hash-related errors though.

**Comment by thecrypticace** [comment]
For now we'll do a `v18` check but I think we can eliminate the check entirely. Fixed in #3251
