### ISSUE TITLE
Mix Not Compiling All Assets - Still Says Successful

### ISSUE THREAD

**Issue by mpierce486** [laravel-mix/laravel-mix#3259]
-   Laravel Mix Version: #.#.# (`npm list --depth=0`)
-   Node Version (`node -v`):
-   NPM Version (`npm -v`):
-   OS:

### Description:

New Laravel project (Laravel Breeze) with Sail. When adding new HTML elements and updating CSS classes (Tailwind), those updates are not reflected in the browser after a reload. I have to run `sail npm run dev` then reload the browser and it will be fine. This happens multiple times.

**Comment by thecrypticace** [comment]
You're editing files outside of docker right? This is a known issue with Docker itself. Filesystem events don't traverse the host <-> container boundary so running `watch` won't always work in Docker. You should be able to work around this by using polling when running the watcher: `npm run watch-poll`
