### ISSUE TITLE
Copying multiple directories produces an error

### ISSUE THREAD

**Issue by Nicolas-S24** [laravel-mix/laravel-mix#3270]
-   Laravel Mix Version: 6.0.44
-   Node Version: 17.4.0
-   NPM Version: 8.6.0
-   OS:

### Description:
Copying multiple directories, e.g. mix.copy(['./resources/fonts', './resources/vendor/package/fonts'], 'public/fonts'), produces an error.

Error: EEXIST: file already exists, mkdir '/ANYPATH/public/fonts'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/ANYPATH/public/fonts'
}

Works fine with version 6.0.43

**Comment by thecrypticace** [comment]
_sigh_ thanks for the report. I'll look at it and get a release out today.

**Comment by thecrypticace** [comment]
Fixed in https://github.com/laravel-mix/laravel-mix/commit/40c2d6c72a528e5edc041d529d41c27ffac7aaa4

Published v6.0.45 — sorry for the trouble and thanks for reporting this!
