### ISSUE TITLE
Should files like `.htaccess` be included in `mix-manifest.json`?

### ISSUE THREAD

**Issue by maciek-szn** [laravel-mix/laravel-mix#3272]
-   Laravel Mix Version: 6.0.45 (`npm list --depth=0`)
-   Node Version (`node -v`): 16.15.0
-   NPM Version (`npm -v`): 8.10.0
-   OS: Windows 10

I don't know if it's an issue, so it's just a question. After upgrading to 6.0.44/6.0.45 I see many new files in my `mix-manifest.json`, including special files like `.htaccess`. Is it correct?

Additional info: `.htaccess` file exists in `public_html/images` directory. It doesn't exist in source directory `resources/img`. Here is the `webpack.mix.js` directive:

`mix.copyDirectory('resources/img', 'public_html/images');`

**Comment by thecrypticace** [comment]
When copying directories we now include all files in the directory in the manifest. The inclusion of hidden files is certainly not intentional though.

**Comment by thecrypticace** [comment]
Fixed in https://github.com/laravel-mix/laravel-mix/commit/58eda8774d4920ecae5cb0697b5501935a30267b
