### ISSUE TITLE
Nesting of Vue single file components not working with Tailwind

### ISSUE THREAD

**Issue by stephan-v** [laravel-mix/laravel-mix#3276]
-   Laravel Mix Version: 6.0.6
-   Node Version: 16.13.0
-   NPM Version: 8.1.0
-   OS: MacOS 12.4

### Description:

I have a Laravel Mix setup with Tailwind, my `webpack.mix.js` file looks like this:

```
mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss/nesting'),
        require('tailwindcss'),
        require('postcss-easing-gradients'),
    ])
    .vue();
```

Now I expected that adding the line `require('tailwindcss/nesting')` would be enough to get indentation working but it seems that even directives like `@apply` are not working within the style block of my Vue components.

I am running Vue loader 16.8.3 and I see a lot of outdated information that postcss processing it applied automatically but starting from v15 this no longer seems the case according to their docs:

> Vue Loader v15 no longer applies PostCSS transforms by default. You will need to use PostCSS via postcss-loader.

According to the Vue Loader docs they then suggest installing the `postcss-loader`:

![image](https://user-images.githubusercontent.com/2384912/172791796-b95a75b8-0b06-4282-80df-a187c2e16923.png)

This still leads to a failing build. The docs are currently missing any information on this.

The assumption is that due to the fact that vue-loader no longer applies PostCSS transforms by default that I now need to start using `<style lang="postcss" scoped>`. 

This still leads to syntax errors though. I am confused what the setup should be though in this case.

**Comment by thecrypticace** [comment]
You need to use `mix.options` for global postcss plugins. mix.postCss applies those plugins to just that one file (and any files it includes if using `postcss-import`)

**Comment by stephan-v** [comment]
Ok this is kind of confusing and not clearly stated in the docs, perhaps it would be nice to add some more information about this in the documentation since having something as basic  as indentation is something which a lot of developers are looking for.
