### ISSUE TITLE
v-slot / typescript error in template using `<script setup lang="ts">`

### ISSUE THREAD

**Issue by albertcito** [laravel-mix/laravel-mix#3290]
-   Laravel Mix Version: 6.0.49
-   Vue Version: 3.2.37
-   Node Version: 16.13.2
-   NPM Version: 8.1.2
-   OS: MacOS Monterey 12.4

### Description:
I'm having an error with `v-slot` and `typescript`. 

1. If I pass variables from a parent component to a child component. In this way `v-slot="{ required, classes, name }"` And ran: `mix --production` it return this error

> TS7031: Binding element 'required' implicitly has an 'any' type.

2. If I modified the code and added `any` in this way: `v-slot="{ required, classes, name }: any"`. And ran `mix --production` it works properly. But if I ran `mix watch` it return an error:

> VueCompilerError: Error parsing JavaScript expression: Unexpected token, expected "," (1:28) at CustomForm.vue:31:15
> 29 |      </FormItem>
> 30 |      <FormItem
> 31 |        v-slot="{ required, classes, name }: any"

### Steps To Reproduce:

 Create parent component  with an slot with bind, like:

```vue
<slot
      v-bind="{
        required,
        classes: inputClasses,
        name: field.name,
        disabled,
      }"
/>
```
Create a component using `<script setup lang="ts">` Call that parent component and call the variables in v-slot.

```vue
<FormItem v-slot="{ required, classes, name }">
  <select
    :name="name"
    :class="classes"
    :required="required"
  >
    <option
      v-for="option in options"
      :key="option.key"
      :value="option.key"
    >
      {{ options.value }}
    </option>
  </select>
</FormItem>
```

Run `mix --production` It will return and error. If you add `any` to those values and run `mix watch` it will return other error.

**Comment by Kwaadpepper** [comment]
You can do something like this :

```v-slot="{ required, classes, name }: { required: boolean, classes: string, name: string }"```

This way you wont be forced to use `any` I think this is a limitation. And it may be related to ts-loader vue-loader ?

**Comment by albertcito** [comment]
Thank you for your answer. Your solutions works properly. Also I added in template `<!-- eslint-disable @typescript-eslint/no-explicit-any -->` and it didn't display TS error if I use `any`.

This is my `webpack.mix.js` file

```javascript
const mix = require('laravel-mix');
const path = require('path');
const { BugsnagSourceMapUploaderPlugin } = require('webpack-bugsnag-plugins')

mix
  .ts('resources/js/app.ts', 'public/js')
  .ts('resources/js/enroll.ts', 'public/js')
  .vue()
  .extract()
  .postCss('resources/css/app.css', 'public/css', [
    require('tailwindcss'),
  ])
  .webpackConfig({
     resolve: {
      extensions: ['*', '.js', '.vue', '.ts'],
      alias: {
        '@': path.resolve(__dirname, 'resources/js/'),
      },
    }
  });

if (mix.inProduction()) {
  const version = mix.version();
}
```

**Comment by Kwaadpepper** [comment]
You should avoid allowing any, as it just remove the benefit of typescript forcing types every where. In my experience I always found a way to declare types somehow. I just use ignore for libraries that does not provide any type script déclaration.
